from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import uuid
from datetime import datetime

from services.audit_log import save_entry, load_log
from services.appeals import submit_appeal
from detectors.llm_detector import analyze_text
from detectors.stylometric import analyze_style

app = Flask(__name__)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

def get_label(confidence):
    if confidence >= 0.75:
        return (
            "Likely AI-generated. Our system detected multiple indicators associated "
            "with AI-generated writing."
        )
    elif confidence >= 0.45:
        return (
            "Uncertain. Our system could not confidently determine whether this "
            "content was written by a human or generated by AI."
        )
    else:
        return (
            "Likely Human-written. No strong indicators of AI-generated writing "
            "were detected."
        )


@app.route("/")
def home():
    return jsonify({
        "message": "Welcome to Provenance Guard API"
    })


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():

    data = request.get_json()

    creator_id = data.get("creator_id")
    text = data.get("text")

    # Signal 1 - Groq LLM
    llm = analyze_text(text)

    # Signal 2 - Stylometric
    style_score = analyze_style(text)

    # Combine scores
    confidence = round(
        (llm["confidence"] * 0.6) + (style_score * 0.4),
        2
    )

    label = get_label(confidence)

    response = {
        "content_id": str(uuid.uuid4()),
        "creator_id": creator_id,
        "text": text,
        "timestamp": datetime.utcnow().isoformat(),

        "attribution": llm["attribution"],

        "llm_score": llm["confidence"],
        "stylometric_score": style_score,

        "confidence": confidence,

        "label": label,

        "status": "classified"
    }

    save_entry(response)

    return jsonify(response)


@app.route("/log", methods=["GET"])
def get_log():
    return jsonify(load_log())


@app.route("/appeal", methods=["POST"])
def appeal():

    data = request.get_json()

    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning")

    success = submit_appeal(content_id, creator_reasoning)

    if success:
        return jsonify({
            "message": "Appeal submitted successfully.",
            "status": "under_review"
        })

    return jsonify({
        "message": "Content ID not found."
    }), 404


if __name__ == "__main__":
    app.run(debug=True)